<?php

/**
 * @file
 * Display Suite install file.
 */

/**
 * Implements hook_install().
 */
function ds_install() {
  module_set_weight('ds', 1);
}

/**
 * Implements hook_uninstall().
 */
function ds_uninstall() {
  // @todo doesn't config clean this up for us automatically nowadays ?
  Drupal::config('ds.classes')->delete();
  Drupal::config('ds.settings')->delete();
}

/**
 * Update to CMI.
 */
function ds_update_8000() {
  // @todo
}
