<?php
// $Id$

/**
 * @file
 * Administrative interface to display suite.
 */

/**
 * Implementation of hook_perm().
 */
function ds_ui_perm() {
  require_once('includes/ds.registry.inc');
  return _ds_ui_perm();
}

/**
 * Implementation of hook_menu().
 */
function ds_ui_menu() {
  require_once('includes/ds.registry.inc');
  return _ds_ui_menu();
}

/**
 * Implementation of hook_theme().
 */
function ds_ui_theme() {
  require_once('includes/ds.registry.inc');
  return _ds_theme_ui();
}

/**
 * Helper function to check access.
 *
 * @param string $perm_1 a permission.
 * @param string $perm_2 a permission.
 */
function _ds_ui_menu_access($perm_1, $perm_2) {
  if (user_access($perm_1) && user_access($perm_2)) {
    return TRUE;
  }
  return FALSE;
}
