<?php

/**
 * @file
 * Display Suite code install file.
 */

/**
 * Implements hook_disable().
 */
function ds_code_disable() {
  drupal_set_message(t('The Display Suite Format module has been disabled. Any existing content that was using the Display Suite code filter will now be visible in plain text. This might pose a security risk by exposing sensitive information, if any, used in the PHP code.'));
}

