<?php
// $Id$

/**
 * @file
 * Display Suite search install file.
 */

/**
 * Implements hook_uninstall().
 */
function ds_search_uninstall() {
  variable_del('ds_search_type');
  variable_del('ds_search_variables');
  variable_del('ds_search_highlight');
  variable_del('ds_search_highlight_selector');
  variable_del('ds_search_show_title');
  variable_del('ds_search_apachesolr_hide_current_filters');
  variable_del('ds_search_apachesolr_language');
}