<?php
// $Id$

/**
 * @file
 * Display Suite switch view modes.
 */

/**
 * Implements hook_permission().
 */
function ds_switch_vm_permission() {

  $permissions = array();
  foreach (node_type_get_names() as $key => $name) {
    $permissions['ds_switch_vm ' . $key] = array(
      'title' => t('Switch view modes on :type', array(':type' => $name))
    );
  }

  return $permissions;
}

/**
 * Implements hook_node_view_alter().
 */
function ds_switch_vm_node_view_alter(&$build) {
  if (node_is_page($build['#node']) && !empty($build['#node']->ds_switch_vm)) {
    $build['#view_mode'] = $build['#node']->ds_switch_vm;
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function ds_switch_vm_form_node_form_alter(&$form, $form_state, $form_id) {

  if (user_access('ds_switch_vm ' . $form['#node']->type) ) {

    $view_mode_settings = field_view_mode_settings('node', $form['#node']->type);

    // Get the view modes.
    $options = array('' => t('Default'));
    $ds_vm = ds_entity_view_modes('node');
    foreach ($ds_vm as $key => $item) {
      $overriden = (!empty($view_mode_settings[$key]['custom_settings']) ? TRUE : FALSE);
      if ($overriden) {
        $options[$key] = $item['label'];
      }
    }

    // Only fire if we have more than 1 option.
    if (count($options) > 1) {
      $node = $form['#node'];
      $form['ds_switch'] = array(
        '#type' => 'fieldset',
        '#title' => t('Display settings'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#group' => 'additional_settings',
        '#weight' => 100,
      );

      $form['ds_switch']['ds_switch_vm'] = array(
        '#type' => 'select',
        '#title' => t('View mode'),
        '#options' => $options,
        '#default_value' => isset($node->ds_switch_vm) ? $node->ds_switch_vm : '',
        '#description' => t('Switch to a different view mode to display the default full page view of this node.'),
        '#weight' => -1,
      );
    }
  }
}
