<?php

/**
 * @file
 * Install file.
 */

/**
 * Implements hook_install().
 */
function ds_panels_install() {
  db_update('system')
    ->fields(array('weight' => 2))
    ->condition('name', 'ds_panels')
    ->execute();
}

/**
 * Implements hook_schema().
 */
function ds_panels_schema() {
  $ds_cache_table['cache_ds_panels'] = drupal_get_schema('cache');
  unset($ds_cache_table['cache_ds_panels']['name']);
  unset($ds_cache_table['cache_ds_panels']['module']);
  return $ds_cache_table;
}