<?php

/**
 * @file
 * Display Suite forms integration.
 */

/**
 * Implements hook_menu().
 */
function ds_forms_menu() {
  $items = array();

  $items['admin/structure/ds/forms'] = array(
    'title' => 'Forms',
    'description' => 'Displays a list of forms which can be styled.',
    'page callback' => 'ds_forms_list',
    'access arguments' => array('admin_display_suite'),
    'file' => 'ds_forms.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_ds_forms_info().
 */
function ds_forms_ds_forms_info() {
  module_load_include('inc', 'ds_forms', 'ds_forms.admin');
  return _ds_forms_ds_forms_info();
}

/**
 * Get the registered forms.
 *
 * @param $reset
 *   Whether to reset the internal and database cache.
 */
function ds_forms_get_forms($reset = FALSE) {
  static $forms = NULL;

  if (!isset($forms)) {
    if ($cache = cache_get('ds_forms') && !$reset) {
      $forms = $cache->data;
    }
    else {
      $forms = module_invoke_all('ds_forms_info');
      cache_set('ds_forms', $forms, 'cache');
    }
  }

  return $forms;
}

/**
 * Implements hook_theme().
 */
function ds_forms_theme() {
  $theme_functions = array();

  // Node form theme function registration.
  $theme_functions['node_form'] = array(
    'render element' => 'form',
  );

  // Display suite theme form registration.
  $theme_functions['ds_forms_custom_form'] = array(
    'render element' => 'form',
  );

  return $theme_functions;
}

/**
 * Implements hook_ds_layout_info().
 */
function ds_forms_ds_layout_info() {
  $path = drupal_get_path('module', 'ds_forms');

  $layouts = array(
    'ds_form' => array(
      'label' => t('2 column stacked'),
      'path' => $path . '/layouts/ds_form',
      'regions' => array(
        'header' => t('Header'),
        'left' => t('Left'),
        'right' => t('Right'),
        'footer' => t('Footer')
      ),
      'css' => TRUE,
      'form' => TRUE,
    ),
  );

  return $layouts;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ds_forms_form_field_ui_field_overview_form_alter(&$form, &$form_state) {

  // We currently only work on node forms or custom forms.
  if ($form['#entity_type'] == 'node' || isset($form_state['ds_custom_form'])) {

    // Add necessary variables.
    $form['#view_mode'] = 'form';
    $form_state['no_view_mode_suggestions'] = TRUE;

    // Attach js.
    $form['#attached']['js'][] = drupal_get_path('module', 'ds_forms') . '/ds_forms.admin.js';

    // Load Display suite.
    form_load_include($form_state, 'inc', 'ds', 'ds.field_ui');
    ds_field_ui_fields_layouts($form, $form_state);

    if (!module_exists('field_group')) {

      $form['#attached']['css'][] = drupal_get_path('module', 'ds_forms') . '/ds_forms.admin.css';

      // Add AJAX wrapper.
      $form['fields']['#prefix'] = '<div id="field-display-overview-wrapper">';
      $form['fields']['#suffix'] = '</div>';

      $form['refresh_rows'] = array('#type' => 'hidden');
      $form['refresh'] = array(
        '#type' => 'submit',
        '#value' => t('Refresh'),
        '#op' => 'refresh_table',
        '#submit' => array('field_ui_display_overview_multistep_submit'),
        '#ajax' => array(
          'callback' => 'field_ui_display_overview_multistep_js',
          'wrapper' => 'field-display-overview-wrapper',
          'effect' => 'fade',
          // The button stays hidden, so we hide the AJAX spinner too. Ad-hoc
          // spinners will be added manually by the client-side script.
          'progress' => 'none',
        ),
      );
    }
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function ds_forms_field_extra_fields() {
  $extra = array();

  foreach (node_type_get_types() as $type) {

    // Get the action buttons.
    $extra['node'][$type->type] = array(
      'form' => array(
        'actions' => array(
          'label' => t('Actions'),
          'weight' => -5,
        ),
      ),
    );

    // Additional settings is exposed if field group is not enabled.
    if (!module_exists('field_group')) {
      $extra['node'][$type->type]['form']['additional_settings'] = array(
        'label' => t('Additional settings'),
        'weight' => -6,
      );
    }

    // Translation support.
    if (module_exists('translation') && translation_supported_type($type->type)) {
      $extra['node'][$type->type]['form']['language'] = array(
        'label' => t('Language'),
        'weight' => 0,
      );
    }
  }

  return $extra;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter
 */
function ds_forms_form_node_form_alter(&$form, &$form_state, $form_id) {
  $entity_type = 'node';
  $bundle = $form['#node']->type;
  $view_mode = 'form';
  if ($layout = ds_get_layout($entity_type, $bundle, $view_mode, FALSE)) {
    $form['#attributes']['class'][] = strtr($layout['layout'], '_', '-');
  }
}

/**
 * Node form template preprocess function.
 */
function ds_forms_preprocess_node_form(&$vars) {
  $entity_type = 'node';
  $bundle = $vars['form']['#node']->type;
  $view_mode = 'form';

  if ($layout = ds_get_layout($entity_type, $bundle, $view_mode, FALSE)) {

    // Hide empty regions variable.
    $hide_empty_regions = $layout['settings']['hide_empty_regions'];

    // Theme hook suggestions.
    $vars['theme_hook_suggestions'][] = $layout['layout'];
    $vars['theme_hook_suggestions'][] = $layout['layout'] . '__' . $entity_type;
    $vars['theme_hook_suggestions'][] = $layout['layout'] . '__' . $entity_type . '_' . $bundle;

    $form = &$vars['form'];

    // Add path to css file.
    if (isset($layout['css'])) {
      drupal_add_css($layout['path'] . '/' . $layout['layout'] . '.css');
    }

    // Add the hidden region.
    $layout['regions']['hidden'] = 'Hidden';

    // Create region variables based on the layout settings.
    foreach ($layout['regions'] as $region_name => $region) {

      // Create the region content.
      if ($region_name == 'hidden') {
        ds_forms_render_region($form, $region_name, $layout);
      }
      else {
        $vars[$region_name] = ds_forms_render_region($form, $region_name, $layout);

        // Hide empty regions.
        if ($hide_empty_regions && empty($vars[$region_name]) && empty($layout['flexible'])) {
          $vars[$region_name] = FALSE;
        }
        elseif (empty($vars[$region_name])) {
          $vars[$region_name] = '&nbsp;';
        }
      }

      // Add extras classes to the region.
      $vars[$region_name . '_classes'] = !empty($layout['settings']['classes'][$region_name]) ? ' ' . implode(' ', $layout['settings']['classes'][$region_name]) : '';
    }
  }
}

/**
 * Render a form region.
 *
 * @param $content
 *   An array of content fields.
 * @param $region
 *   The name of region to render.
 * @param $layout
 *   The layout definition.
 */
function ds_forms_render_region(&$content, $region, $layout) {
  $output = '';

  if (isset($layout['settings']['regions'][$region])) {
    foreach ($layout['settings']['regions'][$region] as $key => $field) {
      if ($region == 'hidden') {
        $content[$field]['#access'] = FALSE;
      }
      else {
        $output .= drupal_render($content[$field]);
      }
    }
  }
  return $output;
}
