<?php

/**
 * @file
 * Display Suite UI.
 */

define('DS_FIELD_TYPE_CODE', 'code_field');
define('DS_FIELD_TYPE_BLOCK', 'block_field');
define('DS_FIELD_TYPE_PREPROCESS', 'preprocess_field');

/**
 * Implements hook_permission().
 */
function ds_ui_permission() {
  return array(
    'admin fields' => array(
      'title' => t('Administer fields'),
      'description' => t('Manage fields for every entity.')
    ),
    'admin classes' => array(
      'title' => t('Administer classes'),
      'description' => t('Manage classes.')
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ds_ui_menu() {
  $items = array();

  // Custom CSS classes.
  $items['admin/structure/ds/classes'] = array(
    'title' => 'CSS classes',
    'route_name' => 'ds_classes',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
  );

  // Fields.
  $items['admin/structure/ds/fields'] = array(
    'title' => 'Fields',
    'route_name' => 'fields_list',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/structure/ds/fields/manage/%'] = array(
    'title' => 'Manage fields',
    'route_name' => 'manage_field',
  );
  $items['admin/structure/ds/fields/delete/%'] = array(
    'title' => 'Delete a field',
    'description' => 'Delete a field.',
    'route_name' => 'delete_field',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
  );
  // Code field
  $items['admin/structure/ds/fields/manage_code'] = array(
    'title' => 'Add a code field',
    'route_name' => 'add_code_field',
  );
  $items['admin/structure/ds/fields/manage_code/%'] = array(
    'title' => 'Edit a code field',
    'description' => 'Manage a field',
    'route_name' => 'manage_code_field',
  );
  // Preprocess field
  $items['admin/structure/ds/fields/manage_preprocess'] = array(
    'title' => 'Add a preprocess field',
    'route_name' => 'add_preprocess_field',
  );
  $items['admin/structure/ds/fields/manage_preprocess/%'] = array(
    'title' => 'Edit a preprocess field',
    'description' => 'Manage a preprocess field',
    'route_name' => 'manage_preprocess_field'
  );
  // Block can be disabled.
  // @todo blocks have changed completely - also do some sort of library thing ?
  /*
  if (module_exists('block')) {
    $items['admin/structure/ds/fields/manage_block'] = array(
      'title' => 'Add a block field',
      'description' => 'Adds a block field',
      'rout_name' => 'add_block_field'
      'type' => MENU_LOCAL_ACTION,
      'weight' => 2,
    );
  if (module_exists('block')) {
    $items['admin/structure/ds/fields/manage_block'] = array(
      'title' => 'Edit a block field',
      'description' => 'Edit a block field',
      'rout_name' => 'manage_block_field'
      'type' => MENU_LOCAL_ACTION,
      'weight' => 2,
    );
  }*/

  return $items;
}
